In [1]:
import geopandas as gpd
import pandas as pd
import os
import numpy as np

In [2]:
df = pd.read_excel('/Users/guilhermeiablonovski/Dropbox (SDSN)/SDG Geospatial Indicators Project/sdg-roadinfrastructure/_processed_data/2023_RAI.xlsx')

In [3]:
df

,iso3,name,region,status,Total Rural Population (SMOD/WorldPop),RAI (SEDAC by SDSN),RAI (ReCAP by SDSN),RAI (GDP corrected),difference,difference2,WB region,WB income group,2021 GDP per capita,2021 HDI,2021 GINI
0,KNA,Saint Kitts and Nevis,Caribbean,Member State,1.130176e+04,0.982459,1.000000,1.000000,1.754090e-02,0.000000,Latin America & Caribbean,High income,18082.610191,0.777,NaN
1,KIR,Kiribati,Micronesia,Member State,0.000000e+00,1.000000,1.000000,1.000000,1.430492e-10,0.000000,East Asia & Pacific,Lower middle income,1606.462514,0.624,27.8
2,MLT,Malta,Southern Europe,Member State,3.920415e+04,1.000000,1.000000,1.000000,7.818801e-11,0.000000,Middle East & North Africa,High income,33486.671984,0.918,31.4
3,TUV,Tuvalu,Polynesia,Member State,0.000000e+00,1.000000,1.000000,1.000000,0.000000e+00,0.000000,East Asia & Pacific,Upper middle income,5632.002993,0.641,NaN
4,MCO,Monaco,Western Europe,Member State,0.000000e+00,1.000000,1.000000,1.000000,0.000000e+00,0.000000,Europe & Central Asia,High income,234315.460504,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,NaN,Aksai Chin,Eastern Asia,Sovereignty unsettled JammuK-China,2.869006e+03,0.232799,0.411642,0.365811,1.788434e-01,0.045831,East Asia & Pacific,NaN,2256.590000,NaN,NaN
203,PNG,Papua New Guinea,Melanesia,Member State,7.767794e+06,0.191190,0.461517,0.398663,2.703274e-01,0.062854,East Asia & Pacific,Lower middle income,2672.945790,0.558,NaN
204,SSD,South Sudan,Middle Africa,Member State,1.636452e+07,0.101823,0.376403,0.282457,2.745799e-01,0.093945,Sub-Saharan Africa,Low income,1071.780000,0.385,44.1
205,COG,Congo,Middle Africa,Member State,2.787666e+06,0.150483,0.359763,0.305918,2.092798e-01,0.053845,Sub-Saharan Africa,Lower middle income,2290.382891,0.571,NaN
206,NaN,Ilemi Triangle,Northern Africa,Adm. by KEN,4.519691e+04,0.000000,0.204687,0.148458,2.046873e-01,0.056230,Middle East & North Africa,NaN,2081.799855,NaN,NaN

In [4]:
rai_region = df.groupby('WB region').apply(lambda x: np.average(x['RAI (GDP corrected)'], weights=x['Total Rural Population (SMOD/WorldPop)'])).rename("RAI_region")
#sedac_region = df.groupby('WB region').apply(lambda x: np.average(x['RAI (SEDAC by SDSN)'], weights=x['Total Rural Population (SMOD/WorldPop)'])).rename("SEDAC_region")
pop2015 = df.groupby('WB region').apply(lambda x: np.sum(x['Total Rural Population (SMOD/WorldPop)'])).rename("Rural Pop")
weighted_region_wb = pd.concat([rai_region,pop2015], axis=1)

In [5]:
weighted_region_wb

                            RAI_region     Rural Pop
WB region
East Asia & Pacific           0.827737  8.070608e+08
Europe & Central Asia         0.933364  3.016310e+08
Latin America & Caribbean     0.862616  2.146260e+08
Middle East & North Africa    0.756388  1.550956e+08
North America                 0.998385  5.884071e+07
South Asia                    0.805126  6.674598e+08
Sub-Saharan Africa            0.592154  7.394980e+08

In [6]:
rai_region = df.groupby('region').apply(lambda x: np.average(x['RAI (GDP corrected)'], weights=x['Total Rural Population (SMOD/WorldPop)'])).rename("RAI_region")
#sedac_region = df.groupby('region').apply(lambda x: np.average(x['RAI (SEDAC by SDSN)'], weights=x['Total Rural Population (SMOD/WorldPop)'])).rename("SEDAC_region")
pop2015 = df.groupby('region').apply(lambda x: np.sum(x['Total Rural Population (SMOD/WorldPop)'])).rename("Rural Pop")
weighted_region = pd.concat([rai_region,pop2015], axis=1)

In [7]:
weighted_region

                           RAI_region     Rural Pop
region
Australia and New Zealand    0.998919  5.230653e+06
Caribbean                    0.874578  1.819709e+07
Central America              0.884569  5.679137e+07
Central Asia                 0.659844  3.630964e+07
Eastern Africa               0.562745  2.566774e+08
Eastern Asia                 0.849052  5.230281e+08
Eastern Europe               0.968652  1.104906e+08
Melanesia                    0.421406  8.628298e+06
Micronesia                   0.709794  4.961278e+04
Middle Africa                0.479478  1.609469e+08
Northern Africa              0.659301  7.736190e+07
Northern America             0.998385  5.884071e+07
Northern Europe              0.994933  2.141801e+07
Polynesia                    0.888875  1.525500e+05
South America                0.852130  1.396375e+08
South-Eastern Asia           0.791330  2.786499e+08
Southern Africa              0.899108  2.317477e+07
Southern Asia                0.802415  6.901841e+08
Southern Europe              0.987611  4.217515e+07
Western Africa               0.689594  2.657410e+08
Western Asia                 0.760092  1.097507e+08
Western Europe               0.998076  6.077587e+07

In [8]:
rai_region = df.groupby('WB income group').apply(lambda x: np.average(x['RAI (GDP corrected)'], weights=x['Total Rural Population (SMOD/WorldPop)'])).rename("RAI_region")
sedac_region = df.groupby('WB income group').apply(lambda x: np.average(x['RAI (SEDAC by SDSN)'], weights=x['Total Rural Population (SMOD/WorldPop)'])).rename("SEDAC_region")
pop2015 = df.groupby('WB income group').apply(lambda x: np.sum(x['Total Rural Population (SMOD/WorldPop)'])).rename("Rural Pop")
weighted_income = pd.concat([rai_region,sedac_region,pop2015], axis=1)

In [9]:
weighted_income

                     RAI_region  SEDAC_region     Rural Pop
WB income group
High income            0.972848      0.894838  2.721122e+08
Low income             0.528886      0.267411  4.825118e+08
Lower middle income    0.771141      0.546466  1.338137e+09
Upper middle income    0.862803      0.674937  8.500954e+08